from .mres2d import GeneratorMultiRes2D
from .unet2d import GeneratorUNet2D
from .unet3d import GeneratorUNet3D
from .edsr2d import GeneratorEDSR2D
from .edsr3d import GeneratorEDSR3D
from .rrdb2d import GeneratorRRDB2D
from .vdsr3d import GeneratorVDSR3D
from .wdsr3d import GeneratorWDSR3D
from .attn_unet2d import GeneratorAttnUNet2D
from .branch_unet2d import GeneratorBranchUNet2D
from .fboost_unet2d import GeneratorFBoostUNet2D
from .ivdnet2d import GeneratorIVDNet2D
from .series_unet2d import GeneratorSeriesUNet2D
