MODEL:
  TYPE: MMT
  NAME: MMT
  DROP_PATH_RATE: 0.0
  SWIN:
    FINAL_UPSAMPLE: "expand_first"
    EMBED_DIM: 192
    DEPTHS: [ 2, 2, 2, 2]
    DECODER_DEPTHS: [ 2, 2, 2, 1]
    NUM_HEADS: [ 3, 6, 12, 24]
    WINDOW_SIZE: [8, 8]
    IN_CHANS: 1
    OUT_CHANS: 1
    PATCH_SIZE: 8

DATA:
  IMG_SIZE: [512, 512]
