version: "1.0.0"

not_for_clinical_use: False
enable_multiple_jobs: True
all_reports: True
warn_unmatched_series: False

jobs:
  - job_name: "boost_ge"
    series_required:
      - "Bpre_ge"
      - "Bpost_ge"
    slice_location_tolerance: "none"
    fov_tolerance: "none"
    iop_tolerance: "none"
    magnetic_fieldstrength_tolerance: False
    manufacturer_flag: False
    manufacturermodelname_flag: False
    protocolname_flag: False
    pixelspacing_tol: "none"
    columns_tol: "none"
    rows_tol: "none"
    ipp_tolerance: "none"
    slice_thickness_tolerance: "none"
    exec_config:
      series_number_offset: 100
      series_desc_prefix: ""
      series_desc_suffix: " BOOST"
      model_id: "202310021105336-unified"
      slices_per_input: 7
      num_channel_output: 1
      num_rotations: 3
      inference_mpr: True
      reshape_for_mpr_rotate: True
      model_type: 'boost_process'
      pipeline_preproc:
        STEP1:
          op: "MASK"
          param: 
            noise_mask_area: False
            noise_mask_selem: False 
        STEP2:
          op: "SKULLSTRIP"
        STEP3:
          op: "REGISTER"
          param:
            transform_type: "affine"
            use_mask_reg: True
        STEP4:
          op: "SCALEGLOBAL"
          param: 
            num_scale_context_slices : 20
            joint_normalize: False 
            scale_ref_zero_img: False 
      pipeline_postproc:
        STEP1:
          op: "RESCALEGLOBAL"

  - job_name: "boost_siemens"
    series_required:
      - "Bpre_siemens"
      - "Bpost_siemens"
    slice_location_tolerance: 0.1
    fov_tolerance: "none"
    iop_tolerance: "none"
    exec_config:
      series_number_offset: 100
      series_desc_prefix: ""
      series_desc_suffix: " BOOST"
      model_id: "202310021105336-unified"
      slices_per_input: 7
      num_channel_output: 1
      num_rotations: 3
      inference_mpr: True
      reshape_for_mpr_rotate: True
      pipeline_preproc:
        STEP1:
          op: "MASK"
          param: 
            noise_mask_area: False
            noise_mask_selem: False 
            noise_mask_threshold: 0.1
        STEP2:
          op: "SKULLSTRIP"
        STEP3:
          op: "REGISTER"
          param:
            transform_type: "affine"
            use_mask_reg: False
        STEP4:
          op: "SCALEGLOBAL"
          param: 
            num_scale_context_slices : 20
            joint_normalize: True 
            scale_ref_zero_img: False 
      pipeline_postproc:
        STEP1:
          op: "RESCALEGLOBAL"
  - job_name: "boost_philips"
    series_required:
      - "Bpre_philips"
      - "Bpost_philips"
    slice_location_tolerance: 0.1
    fov_tolerance: "none"
    iop_tolerance: "none"
    exec_config:
      series_number_offset: 100
      series_desc_prefix: ""
      series_desc_suffix: " BOOST"
      model_id: "202310021105336-unified"
      slices_per_input: 7
      num_channel_output: 1
      num_rotations: 3
      inference_mpr: True
      reshape_for_mpr_rotate: True
      pipeline_preproc:
        STEP1:
          op: "MASK"
          param: 
            noise_mask_area: False
            noise_mask_selem: False 
        STEP2:
          op: "SKULLSTRIP"
        STEP3:
          op: "REGISTER"
          param:
            transform_type: "affine"
            use_mask_reg: True
        STEP4:
          op: 'HIST'
        STEP5:
          op: "SCALEGLOBAL"
          param: 
            num_scale_context_slices : 20
            joint_normalize: False
            scale_ref_zero_img: False 
      pipeline_postproc:
        STEP1:
          op: "RESCALEGLOBAL"


series:
  - name: "Bpre_ge"
    reg_match: "Bpre"
    reg_exclude: ""
    manufacturer_match: "ge"
    slice_range: [1, 400]
    frame_range: [1, 1]
    modality: "MR"
    equidistance_tolerance: "none"
  - name: "Bpost_ge"
    reg_match: "Bpost"
    reg_exclude: ""
    manufacturer_match: "ge"
    slice_range: [1, 400]
    frame_range: [1, 1]
    modality: "MR"
    equidistance_tolerance: "none"
  - name: "Bpre_philips"
    reg_match: "Bpre"
    reg_exclude: ""
    manufacturer_match: "philips"
    slice_range: [1, 400]
    frame_range: [1, 1]
    modality: "MR"
    equidistance_tolerance: "none"
  - name: "Bpost_philips"
    reg_match: "Bpost"
    reg_exclude: ""
    manufacturer_match: "philips"
    slice_range: [1, 400]
    frame_range: [1, 1]
    modality: "MR"
    equidistance_tolerance: "none"
  - name: "Bpre_siemens"
    reg_match: "Bpre"
    reg_exclude: ""
    manufacturer_match: "siemens"
    slice_range: [1, 400]
    frame_range: [1, 1]
    modality: "MR"
    equidistance_tolerance: "none"
  - name: "Bpost_siemens"
    reg_match: "Bpost"
    reg_exclude: ""
    manufacturer_match: "siemens"
    slice_range: [1, 400]
    frame_range: [1, 1]
    modality: "MR"
    equidistance_tolerance: "none"
