version: "0.0.1"

disable_openvino: True
not_for_clinical_use: True
enable_multiple_jobs: True
all_reports: True
warn_unmatched_series: False

jobs:
  - job_name: "gad_ge"
    series_required:
      - "zero_dose_ge"
      - "low_dose_ge"
    slice_location_tolerance: "none"
    fov_tolerance: "inf"
    exec_config:
      series_number_offset: 100
      series_desc_prefix: "SubtleGAD:"
      series_desc_suffix: ":research_only"
      model_id: "20200304102938-gadge"
  - job_name: "gad_philips"
    series_required:
      - "zero_dose_philips"
      - "low_dose_philips"
    slice_location_tolerance: "none"
    fov_tolerance: "inf"
    exec_config:
      series_number_offset: 100
      series_desc_prefix: "SubtleGAD:"
      series_desc_suffix: ":research_only"
      model_id: "20200304102652-gadphilips"
  - job_name: "gad_siemens"
    series_required:
      - "zero_dose_siemens"
      - "low_dose_siemens"
    slice_location_tolerance: "none"
    fov_tolerance: "inf"
    exec_config:
      series_number_offset: 100
      series_desc_prefix: "SubtleGAD:"
      series_desc_suffix: ":research_only"
      model_id: "20200304102652-gadphilips"

series:
  - name: "zero_dose_ge"
    reg_match: "zerodose"
    reg_exclude: ""
    manufacturer_match: "ge"
    slice_range: [1, 400]
    frame_range: [1, 1]
    modality: "MR"
    equidistance_tolerance: "none"
  - name: "low_dose_ge"
    reg_match: "lowdose"
    reg_exclude: ""
    manufacturer_match: "ge"
    slice_range: [1, 400]
    frame_range: [1, 1]
    modality: "MR"
    equidistance_tolerance: "none"
  - name: "zero_dose_philips"
    reg_match: "zerodose"
    reg_exclude: ""
    manufacturer_match: "philips"
    slice_range: [1, 400]
    frame_range: [1, 1]
    modality: "MR"
    equidistance_tolerance: "none"
  - name: "low_dose_philips"
    reg_match: "lowdose"
    reg_exclude: ""
    manufacturer_match: "philips"
    slice_range: [1, 400]
    frame_range: [1, 1]
    modality: "MR"
    equidistance_tolerance: "none"
  - name: "zero_dose_siemens"
    reg_match: "zerodose"
    reg_exclude: ""
    manufacturer_match: "siemens"
    slice_range: [1, 400]
    frame_range: [1, 1]
    modality: "MR"
    equidistance_tolerance: "none"
  - name: "low_dose_siemens"
    reg_match: "lowdose"
    reg_exclude: ""
    manufacturer_match: "siemens"
    slice_range: [1, 400]
    frame_range: [1, 1]
    modality: "MR"
    equidistance_tolerance: "none"
