version: "0.0.1"

disable_openvino: True
not_for_clinical_use: True
enable_multiple_jobs: True
all_reports: True
warn_unmatched_series: False

jobs:
  - job_name: "reduce_contrast"
    series_required:
      - "zero_dose_series"
      - "low_dose_series"
    slice_location_tolerance: "none"
    fov_tolerance: "inf"
    exec_config:
      series_number_offset: 100
      series_desc_prefix: "SubtleGAD:"
      series_desc_suffix: ":research_only"
      model_id: "tiantan_gad"

series:
  - name: "zero_dose_series"
    reg_match: "zerodose"
    reg_exclude: ""
    slice_range: [1, 400]
    frame_range: [1, 1]
    modality: "MR"
    equidistance_tolerance: "none"
  - name: "low_dose_series"
    reg_match: "lowdose"
    reg_exclude: ""
    slice_range: [1, 400]
    frame_range: [1, 1]
    modality: "MR"
    equidistance_tolerance: "none"
