MODEL:
  TYPE: swin
  NAME: swin_tiny_patch4_window6_192
  DROP_PATH_RATE: 0.2
  PRETRAIN_CKPT: "./pretrained_ckpt/swin_tiny_patch4_window7_224.pth"
  SWIN:
    FINAL_UPSAMPLE: "expand_first"
    EMBED_DIM: 512
    DEPTHS: [ 2, 2, 2, 1]
    DECODER_DEPTHS: [ 2, 2, 2, 1]
    NUM_HEADS: [ 4, 8, 16, 32]
    WINDOW_SIZE: 6
    IN_CHANS: 1
    OUT_CHANS: 1

DATA:
  IMG_SIZE: 192